#pragma once

#include <string>
#include <filesystem> // C++17 Standard Library
#include "root_directory.h" // Generated by CMake

class FileSystem {
public:
    // We return std::string because Assimp/stb_image expect strings, not paths
    static std::string getPath(const std::string& relativePath) {
        // 1. Create a path object from the project root (generated by CMake)
        std::filesystem::path root(logl_root);
        
        // 2. Create a path object from the input
        std::filesystem::path file(relativePath);

        // 3. Combine them safely
        // The / operator automatically adds the correct separator for Mac/Windows
        std::filesystem::path fullPath = root / file;

        // 4. Return as string
        return fullPath.string();
    }
};